In Dart you can capture any exception object that you caught:

```dart
import 'package:sentry/sentry.dart';

try {
  aMethodThatMightFail();
} catch (exception, stackTrace) {
  await Sentry.captureException(
    exception,
    stackTrace: stackTrace,
  );
}
```

## Tips for Catching Errors

- Use a `try/catch` block
- Use a `catchError` block for `Futures`
- `Isolate` errors on the `current` Isolate which is the equivalent of a main/UI thread, e.g. using `Isolate.current.addErrorListener`, are captured automatically (Only for non-Web Apps).
- For your own `Isolates`, add an [Error Listener](https://api.flutter.dev/flutter/dart-isolate/Isolate/addErrorListener.html) by calling `isolate.addSentryErrorListener()`.
- Due to the nature of `async/await`, always call `await` when calling the `Sentry.captureMessage` or `Sentry.captureException`, alternatively, pass the `stackTrace` parameter `Sentry.captureException(exception, stackTrace: stackTrace);` to get the correct stack trace.
